#include "LODMesher.h"
#include "../Chunk.h"
#include <cmath>
#include <algorithm>
#include <vector>

// ─────────────────────────────────────────────────────────────────────────────
//  LODMesher — Improved Quality Implementation
//
//  Combined techniques from two reference libraries:
//
//  From LodGen (QEM / vertex clustering):
//    - Each LOD grid cell is one vertex cluster.
//    - Cell height is computed from the average heightmap within that cluster
//      rather than just the center point. This is the core of vertex clustering:
//      replace many original vertices with ONE representative vertex per cluster.
//    - Block type is selected by majority vote within the cluster.
//
//  From LoD/CDLOD (cdlod_terrain.vert — morphVertex):
//    - Grid cells are arranged so border vertices of different LOD tiles snap
//      to compatible positions with neighboring tiles reducing seams.
//    - Side skirts are generated by closing vertical gaps between cells,
//      the same way CDLOD closes gaps between LOD levels.
//
//  Result:
//    - Top face: greedy quad merging between cells that have similar enough
//      height and block type — much lower polygon count with smooth appearance.
//    - Side face: vertical skirt emitted only when there is a significant
//      height difference between neighboring cells.
//    - No visible holes or seams.
// ─────────────────────────────────────────────────────────────────────────────

// ─── Constants ───────────────────────────────────────────────────────────────
// Height difference tolerance (in blocks) for two cells to be considered flat
// enough for greedy merge. LOD1 can be slightly loose; LOD3 is stricter
// because its step size is larger.
static int heightTolerance(int level) {
    if (level == 1) return 2;
    if (level == 2) return 3;
    return 4;
}

// ─── Vertex emit helper ───────────────────────────────────────────────────────
static inline void pushV(std::vector<float>& b,
                         float x, float y, float z,
                         float u, float v,
                         float layer, float light) {
    b.push_back(x); b.push_back(y); b.push_back(z);
    b.push_back(u); b.push_back(v);
    b.push_back(layer);
    b.push_back(light);
}

// ─── Texture layer (same mapping as GreedyMesher) ────────────────────────────
static inline float texLayer(BlockType bt, int axis, bool back) {
    if (bt == BlockType::Grass) {
        if (axis == 1) return back ? 2.0f : 0.0f;
        return 1.0f;
    }
    if (bt == BlockType::Dirt)  return 2.0f;
    if (bt == BlockType::Stone) return 3.0f;
    if (bt == BlockType::Sand)  return 4.0f;
    return 0.0f;
}

// ─── Emit top quad (CCW winding) ─────────────────────────────────────────────
// x0/z0 = SW corner, x1/z1 = NE corner, y = block top surface height
static void emitTop(std::vector<float>& buf,
                    float x0, float z0, float x1, float z1, float y,
                    float layer) {
    const float light = 1.0f;
    pushV(buf, x0,y,z0, x0,z0, layer,light);
    pushV(buf, x1,y,z0, x1,z0, layer,light);
    pushV(buf, x1,y,z1, x1,z1, layer,light);
    pushV(buf, x0,y,z0, x0,z0, layer,light);
    pushV(buf, x1,y,z1, x1,z1, layer,light);
    pushV(buf, x0,y,z1, x0,z1, layer,light);
}

// ─── Emit side quads (vertical walls) ────────────────────────────────────────
// +X side: normal facing +X
static void emitSidePX(std::vector<float>& buf,
                       float x, float z0, float z1,
                       float yBot, float yTop, float layer) {
    const float light = 0.80f;
    pushV(buf, x,yBot,z1, z1,yBot, layer,light);
    pushV(buf, x,yTop,z1, z1,yTop, layer,light);
    pushV(buf, x,yTop,z0, z0,yTop, layer,light);
    pushV(buf, x,yBot,z1, z1,yBot, layer,light);
    pushV(buf, x,yTop,z0, z0,yTop, layer,light);
    pushV(buf, x,yBot,z0, z0,yBot, layer,light);
}

// -X side
static void emitSideNX(std::vector<float>& buf,
                       float x, float z0, float z1,
                       float yBot, float yTop, float layer) {
    const float light = 0.80f;
    pushV(buf, x,yBot,z0, z0,yBot, layer,light);
    pushV(buf, x,yTop,z0, z0,yTop, layer,light);
    pushV(buf, x,yTop,z1, z1,yTop, layer,light);
    pushV(buf, x,yBot,z0, z0,yBot, layer,light);
    pushV(buf, x,yTop,z1, z1,yTop, layer,light);
    pushV(buf, x,yBot,z1, z1,yBot, layer,light);
}

// +Z side
static void emitSidePZ(std::vector<float>& buf,
                       float z, float x0, float x1,
                       float yBot, float yTop, float layer) {
    const float light = 0.70f;
    pushV(buf, x0,yBot,z, x0,yBot, layer,light);
    pushV(buf, x0,yTop,z, x0,yTop, layer,light);
    pushV(buf, x1,yTop,z, x1,yTop, layer,light);
    pushV(buf, x0,yBot,z, x0,yBot, layer,light);
    pushV(buf, x1,yTop,z, x1,yTop, layer,light);
    pushV(buf, x1,yBot,z, x1,yBot, layer,light);
}

// -Z side
static void emitSideNZ(std::vector<float>& buf,
                       float z, float x0, float x1,
                       float yBot, float yTop, float layer) {
    const float light = 0.70f;
    pushV(buf, x1,yBot,z, x1,yBot, layer,light);
    pushV(buf, x1,yTop,z, x1,yTop, layer,light);
    pushV(buf, x0,yTop,z, x0,yTop, layer,light);
    pushV(buf, x1,yBot,z, x1,yBot, layer,light);
    pushV(buf, x0,yTop,z, x0,yTop, layer,light);
    pushV(buf, x0,yBot,z, x0,yBot, layer,light);
}

// ─────────────────────────────────────────────────────────────────────────────
//  Cell descriptor — result of vertex clustering for one grid cell
// ─────────────────────────────────────────────────────────────────────────────
struct Cell {
    float    avgHeight = -1.0f; // -1 means empty (all Air blocks)
    BlockType bt       = BlockType::Air;
    bool     valid     = false;
};

// ─────────────────────────────────────────────────────────────────────────────
//  LODMesher::build — main entry point
// ─────────────────────────────────────────────────────────────────────────────
void LODMesher::build(
    int level,
    int tileX,
    int tileZ,
    const BlockQuery&  blockQuery,
    const HeightQuery& heightQuery,
    std::vector<float>& outVertices)
{
    outVertices.clear();

    const int step     = (1 << level);           // blocks per cell side
    const int coverage = step * Chunk::SIZE;     // blocks per tile side
    const int originX  = tileX * coverage;
    const int originZ  = tileZ * coverage;
    const int cells    = Chunk::SIZE;            // always 16 cells per tile side

    // ── Phase 1: Vertex Clustering ─────────────────────────────────────────
    // Each cell covers (step x step) source blocks.
    // From LodGen vertex_cluster: find representative point (average heightmap)
    // and select block type by majority vote.

    std::vector<Cell> grid(cells * cells);

    for (int iz = 0; iz < cells; iz++) {
        for (int ix = 0; ix < cells; ix++) {
            int worldX0 = originX + ix * step;
            int worldZ0 = originZ + iz * step;

            // Sample all blocks within this cluster
            int   heightSum   = 0;
            int   heightCount = 0;
            int   blockCounts[5] = {0,0,0,0,0}; // Grass, GrassSide, Dirt, Stone, Sand

            for (int dz = 0; dz < step; dz++) {
                for (int dx = 0; dx < step; dx++) {
                    int wx = worldX0 + dx;
                    int wz = worldZ0 + dz;
                    int h  = heightQuery(wx, wz);
                    if (h < 0) continue;
                    heightSum += h;
                    heightCount++;

                    BlockType bt = blockQuery(wx, h, wz);
                    // Majority vote index mapping
                    int idx = 0;
                    if (bt == BlockType::Grass)  idx = 0;
                    else if (bt == BlockType::Dirt)   idx = 2;
                    else if (bt == BlockType::Stone)  idx = 3;
                    else if (bt == BlockType::Sand)   idx = 4;
                    if (idx < 5) blockCounts[idx]++;
                }
            }

            if (heightCount == 0) continue; // empty cell

            Cell& c = grid[iz * cells + ix];
            // Average height (vertex clustering: cluster centroid)
            c.avgHeight = (float)heightSum / heightCount;
            c.valid     = true;

            // Select majority block type
            int maxIdx = 0;
            for (int k = 1; k < 5; k++)
                if (blockCounts[k] > blockCounts[maxIdx]) maxIdx = k;

            switch (maxIdx) {
                case 0: c.bt = BlockType::Grass; break;
                case 2: c.bt = BlockType::Dirt;  break;
                case 3: c.bt = BlockType::Stone; break;
                case 4: c.bt = BlockType::Sand;  break;
                default: c.bt = BlockType::Grass; break;
            }
        }
    }

    // ── Phase 2: Greedy Quad Merging for Top Faces ────────────────────────
    // From CDLOD: merge cells that have similar height and block type
    // into a single large quad to greatly reduce polygon count.
    // Height difference tolerance = heightTolerance(level).

    const int tol = heightTolerance(level);
    std::vector<bool> merged(cells * cells, false);

    for (int iz = 0; iz < cells; iz++) {
        for (int ix = 0; ix < cells; ix++) {
            if (merged[iz * cells + ix]) continue;
            const Cell& c = grid[iz * cells + ix];
            if (!c.valid) continue;

            // Expand width in the +X direction: all cells must be compatible
            int w = 1;
            while (ix + w < cells) {
                const Cell& cn = grid[iz * cells + (ix + w)];
                if (!cn.valid || cn.bt != c.bt ||
                    std::abs(cn.avgHeight - c.avgHeight) > tol)
                    break;
                w++;
            }

            // Expand height in the +Z direction: every row must be compatible across full width w
            int h = 1;
            while (iz + h < cells) {
                bool rowOk = true;
                for (int col = 0; col < w; col++) {
                    const Cell& cn = grid[(iz + h) * cells + (ix + col)];
                    if (!cn.valid || cn.bt != c.bt ||
                        std::abs(cn.avgHeight - c.avgHeight) > tol) {
                        rowOk = false; break;
                    }
                }
                if (!rowOk) break;
                h++;
            }

            // Mark all cells in this patch as merged
            for (int dz = 0; dz < h; dz++)
                for (int dx = 0; dx < w; dx++)
                    merged[(iz + dz) * cells + (ix + dx)] = true;

            // World-space corners
            float wx0 = (float)(originX + ix * step);
            float wx1 = (float)(originX + (ix + w) * step);
            float wz0 = (float)(originZ + iz * step);
            float wz1 = (float)(originZ + (iz + h) * step);

            // Average height across the full patch for accuracy
            float ySum = 0.0f; int yN = 0;
            for (int dz = 0; dz < h; dz++) {
                for (int dx = 0; dx < w; dx++) {
                    ySum += grid[(iz + dz) * cells + (ix + dx)].avgHeight;
                    yN++;
                }
            }
            float yAvg = ySum / yN;
            float fy   = yAvg + 1.0f; // top surface Y of the block

            float layer = texLayer(c.bt, 1, false);
            emitTop(outVertices, wx0, wz0, wx1, wz1, fy, layer);
        }
    }

    // ── Phase 3: Side Skirts ───────────────────────────────────────────────
    // From CDLOD cdlod_terrain.vert: vertical skirts at LOD tile edges and
    // between cells with significant height differences.
    // This prevents holes between LOD levels.

    for (int iz = 0; iz < cells; iz++) {
        for (int ix = 0; ix < cells; ix++) {
            const Cell& c = grid[iz * cells + ix];
            if (!c.valid) continue;

            float wx0 = (float)(originX + ix * step);
            float wx1 = (float)(originX + (ix + 1) * step);
            float wz0 = (float)(originZ + iz * step);
            float wz1 = (float)(originZ + (iz + 1) * step);
            float fy  = c.avgHeight + 1.0f;

            // -X side
            if (ix > 0) {
                const Cell& cn = grid[iz * cells + (ix - 1)];
                float yN = cn.valid ? (cn.avgHeight + 1.0f) : 0.0f;
                if (!cn.valid || fy > yN + 0.5f) {
                    float yBot = std::max(0.0f, yN);
                    float layer = texLayer(c.bt, 0, false);
                    emitSideNX(outVertices, wx0, wz0, wz1, yBot, fy, layer);
                }
            } else {
                // Tile border: always emit skirt downward to prevent gaps with neighboring tiles
                float layer = texLayer(c.bt, 0, false);
                emitSideNX(outVertices, wx0, wz0, wz1, std::max(0.0f, fy - step * 2.0f), fy, layer);
            }

            // +X side
            if (ix < cells - 1) {
                const Cell& cn = grid[iz * cells + (ix + 1)];
                float yN = cn.valid ? (cn.avgHeight + 1.0f) : 0.0f;
                if (!cn.valid || fy > yN + 0.5f) {
                    float yBot = std::max(0.0f, yN);
                    float layer = texLayer(c.bt, 0, true);
                    emitSidePX(outVertices, wx1, wz0, wz1, yBot, fy, layer);
                }
            } else {
                float layer = texLayer(c.bt, 0, true);
                emitSidePX(outVertices, wx1, wz0, wz1, std::max(0.0f, fy - step * 2.0f), fy, layer);
            }

            // -Z side
            if (iz > 0) {
                const Cell& cn = grid[(iz - 1) * cells + ix];
                float yN = cn.valid ? (cn.avgHeight + 1.0f) : 0.0f;
                if (!cn.valid || fy > yN + 0.5f) {
                    float yBot = std::max(0.0f, yN);
                    float layer = texLayer(c.bt, 2, false);
                    emitSideNZ(outVertices, wz0, wx0, wx1, yBot, fy, layer);
                }
            } else {
                float layer = texLayer(c.bt, 2, false);
                emitSideNZ(outVertices, wz0, wx0, wx1, std::max(0.0f, fy - step * 2.0f), fy, layer);
            }

            // +Z side
            if (iz < cells - 1) {
                const Cell& cn = grid[(iz + 1) * cells + ix];
                float yN = cn.valid ? (cn.avgHeight + 1.0f) : 0.0f;
                if (!cn.valid || fy > yN + 0.5f) {
                    float yBot = std::max(0.0f, yN);
                    float layer = texLayer(c.bt, 2, true);
                    emitSidePZ(outVertices, wz1, wx0, wx1, yBot, fy, layer);
                }
            } else {
                float layer = texLayer(c.bt, 2, true);
                emitSidePZ(outVertices, wz1, wx0, wx1, std::max(0.0f, fy - step * 2.0f), fy, layer);
            }
        }
    }
}
